server:
  port: ${PORT}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  phone-number: ${TWILIO_PHONE_NUMBER}

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

sendgrid:
  api-key: ${SENDGRID_API_KEY}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

